---
- name: D茅ploiement complet plateforme Wikijs SaaS
  hosts: wikijs_servers
  become: true

  #  On charge les variables globales et les instances fixes
  vars_files:
    - group_vars/all.yml   # Contient wikis_docker (ia/devops/cyber) + base_domain + kc_clients

  #  tape 1 : Installation et configuration de la plateforme commune
  roles:
   
    - role: wiki-essaie  # R么le de gestion des instances Wiki.js
    - role: n8n          # R么le de gestion de n8n (automatisation low-code)
    - role: portal       # R么le de gestion du portail d'accueil
    - role: provisioner  # R么le de gestion du service de provisioning des instances Wiki.js